install: true

script: true

after_success:
- pip install awscli --upgrade --user
- zip -r myLambda.zip myLambda
- aws s3 mv myLambda.zip s3://$lambda_functions_s3_bucket/myLambda.zip
- aws --region us-east-1 lambda update-function-code --function-name myLambdaFunction --s3-bucket $lambda_functions_s3_bucket --s3-key myLambda.zip
